### ISSUE TITLE
E_ERROR from file class-postmark-debug.php

### ISSUE THREAD

**Issue by pgraham3** [ActiveCampaign/postmark-wordpress#95]
In version 1.17.0 (latest) a couple customers reported issues with the new Site Health addition. Reverted stable to v1.16.1 for now until we fix it.

Error

> An error of type E_ERROR was caused in line 99 of the file /home/utag/public_html/wp-content/plugins/postmark-approved-wordpress-plugin/includes/class-postmark-debug.php. Error message: Uncaught TypeError: Postmark_Debug::strbool(): Argument #1 ($value) must be of type bool, null given, called in /home/utag/public_html/wp-content/plugins/postmark-approved-wordpress-plugin/includes/class-postmark-debug.php on line 64 and defined in /home/utag/public_html/wp-content/plugins/postmark-approved-wordpress-plugin/includes/class-postmark-debug.php:99
Stack trace:
#0 /home/utag/public_html/wp-content/plugins/postmark-approved-wordpress-plugin/includes/class-postmark-debug.php(64): Postmark_Debug->strbool()
#1 /home/utag/public_html/wp-includes/class-wp-hook.php(307): Postmark_Debug->debug_info()
#2 /home/utag/public_html/wp-includes/plugin.php(191): WP_Hook->apply_filters()
#3 /home/utag/public_html/wp-admin/includes/class-wp-debug-data.php(1461): apply_filters()
#4 /home/utag/public_html/wp-admin/site-health-info.php(32): WP_Debug_Data::debug_data()
#5 /home/utag/public_html/wp-admin/includes/class-wp-site-health.php(66): require_once(‘/home/utag/publ…’)
#6 /home/utag/public_html/wp-includes/class-wp-hook.php(307): WP_Site_Health->show_site_health_tab()
#7 /home/utag/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#8 /home/utag/public_html/wp-includes/plugin.php(476): WP_Hook->do_action()
#9 /home/utag/public_html/wp-admin/site-health.php(205): do_action()
#10 {main}
thrown

https://wordpress.org/support/topic/1-17-0-update-throw-a-wp-error-notification/#post-15752616

https://wordpress.org/support/topic/an-error-of-type-e_error-was-caused-in-line-99-of-the-file/#post-15750328

**Comment by pgraham3** [comment]
Hello @bhubbard! 

We had a couple reports over the weekend of [this PR](https://github.com/ActiveCampaign/postmark-wordpress/pull/92/files) causing an error. 

Do you mind taking a look when you get a chance? I reverted to previous version of plugin for now in the marketplace.

One customer confirmed using WordPress 6.0 and PHP 8.0.7 when seeing the error.
